name: Weekly standup

on:
  schedule:
    - cron: "0 12 * * 6"  # Saturday at noon
  workflow_dispatch:

jobs:
  weekly_meeting:
    name: create new issue
    runs-on: ubuntu-latest
    steps:
    - name: Set Date
      run: echo "TODAY=$(date -u '+%B %d %Y')" >> $GITHUB_ENV

    - name: Create issue
     # Get the title, labels, assignees, and body of the issue template at the path
      uses: imjohnbo/extract-issue-template-fields@v1
      id: extract
      with:
        path: .github/ISSUE_TEMPLATE/weekly.md

    # Create new issue with assignees, labels, title, and body
    - uses: imjohnbo/issue-bot@v3
      id: create-issue
      with:
        assignees: "skymob, lizzysoltis"
        labels: "standup"
        pinned: true
        close-previous: true
        linked-comments: true
        title: "${{ steps.extract.outputs.title }} - ${{ env.TODAY }}"
        body: ${{ steps.extract.outputs.body }}

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
